apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-py
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-py
  template:
    metadata:
      labels:
        app: api-py
    spec:
      containers:
        - name: api-py
          image: 514994861653.dkr.ecr.ap-south-1.amazonaws.com/multi-cicd-api-py:latest
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api-py-service
spec:
  selector:
    app: api-py
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
